### PR TITLE
Fix 0.6 errors and warnings

### LINKED ISSUE #92: Tests fail on nightly due to `:zip` becoming `Expr(:globalref, Main, :zip)`
`ArgumentError: unknown or unsupported iterator $(Expr(:globalref, Main, :zip)) in @itr macro`

Ex: https://travis-ci.org/JuliaLang/Iterators.jl/jobs/183796259

### PR DESCRIPTION
**Pull request by iamed2**
Fixed #92 

Fixed Array constructor deprecation

Fixed Base => Base.Iterators deprecations

### CODE REVIEW

File: src/Iterators.jl [hunk 1]
```diff
@@ -183,7 +188,7 @@ function start(it::Product)
             return js, nothing
         end
     end
-    vs = Array(Any, n)
+    vs = Array{Any}(n)
```
Comment (tkelman) [inline src/Iterators.jl]: it's good to do `Vector` for this so the compiler can do less work with determining the number of dimensions
